dist: trusty
sudo: true
language: python
python:
  - 2.7
  - 3.6
  - pypy-5.4.1
  - pypy3.3-5.2-alpha1
  - 2.6
  - 3.3
  - 3.4
  - 3.5
  - nightly
env:
  - BACKEND=python
  - BACKEND=yajl2
  - BACKEND=yajl2-cffi
before_install:
  - sudo apt-get -qq update
  - if [[ $BACKEND == yajl2* ]]; then sudo apt-get install -y libyajl2 libyajl-dev; fi
install:
  - travis_retry pip install coveralls
  - travis_retry pip install tox-travis
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install pyOpenSSL>=16.2.0; fi
script:
  - export YAJL2_VERSION=">=2.0.0, <2.0.5"
  - tox
after_success:
  - coveralls
  - python setup.py bdist_wheel sdist
